### ISSUE TITLE
Update first-threejs-scene blog post

### ISSUE THREAD

**Issue by arthurdenner** [chicio/chicio.github.io#74]
Hi! 👋🏽 

I recently found your blog post ["A physically based scene with three.js"](https://www.fabrizioduroni.it/2017/05/13/first-threejs-scene/) and found it very interesting - thanks for writing it!

Because it's a post from 2017, when I was trying to reproduce the example, I had to dig into the old blog repo to find the models and into the three.js versions to find a compatible one. Took me some time but I managed to do it. 🎉 

I'm opening this issue to request an update to the blog post and to this repo to provide up-to-date instructions so that others can continue to enjoy and learn from it.

I created a [sandbox](https://codesandbox.io/s/threejs-tutorial-vanillajs-tj1ty?file=/index.html) with an HTML setup that works in case you want to copy it.
There are some warnings related to deprecated properties, I didn't investigate deeper on those, but the example runs fine.

The assets are located [in the old repo](https://github.com/chicio/old.chicio.github.io/tree/master/assets/models). They're also included in the sandbox.

If I may, I'd suggest linking the sandbox in the blog post - you can either link mine or fork it and link from your account.
In any case, I think it's much easier to present the post with a runnable example.

Let me know if I can help with anything regarding this. 🙌🏽 

Thanks for the post once again.
Best regards!

**Comment by chicio** [comment]
Hi @arthurdenner ,

thank you so much for your feedback. I really appreciate it!! 🥳 I added  the link to the sandbox in the article (with a reference to you for the contribution). It will be visible after the Cloudflare cache purge.

Thank you again for the contribution.
Fabrizio.

**Comment by arthurdenner** [comment]
@chicio, no worries! Thank you for the shoutout and best regards. 🤜🏽 🤛🏽
